

test:
   EXPERIMENT: 'exp_small_46/test'
   MARKER_SIZE: '1.25x1.25_2x2'
   MARKER_ID: 'markerARUCO3_5'
   FOV: 46
   MIN_Z: 5
   MAX_Z: 120
   MIN_X: -5
   MAX_X: 5
   MIN_Y: -5
   MAX_Y: 5
   LOOK_TO_ORIGIN: FalseTrue
   THETA_MAX: 82
   DELTA_DISTANCE: 5
   IMAGE_FORMAT: 'jpeg'